accounts/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin
from . import views


app_name = 'accounts'


urlpatterns = [
    path('api/get_user/', views.get_logged_in_user, name='login_user_api'),
    path('register/', views.registration_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('', views.home, name="home"),
    path('tasks/<slug:category>', views.home, name="categories"),
    path('tasks/<slug:category>/<str:task_uuid>', views.home, name="tasks"),
    path('profile', views.home, name="profile"),
]

course/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin
from . import views

app_name = 'course'

urlpatterns = [
    path('get_categories/', views.category_view, name='category'),
    path('get_tasks/<slug:slug>', views.task_view, name='task'),
    path('profile/', views.profile_view, name='profile'),
    path('upload/', views.submission, name='submit'),
    path('get_certificate/<slug:category_slug>',
         views.get_certificate, name="get_certificate"),
]

summerschool/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('api/course/', include('course.urls')),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html'), name='password_reset'),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
     name='password_reset_complete')   
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.utils import timezone



class MyAccountManager(BaseUserManager):
    def create_user(self, email,password=None,**kwargs):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
			**kwargs
		)
        
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_superuser(self, email, password,**kwargs):
        user = self.create_user(
			email=self.normalize_email(email),
			password=password,
			**kwargs
		)
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user
 


class Account(AbstractBaseUser, PermissionsMixin):
    email=models.EmailField(verbose_name="email", max_length=160, unique=True)
    registration_number=models.CharField(max_length=9, unique=True)
    first_name= models.CharField(max_length=100)
    last_name= models.CharField(max_length=100)
    date_joined = models.DateTimeField(default=timezone.now)
    last_login=models.DateTimeField(default=timezone.now)
    is_admin=models.BooleanField(default=False)
    is_active=models.BooleanField(default=True)
    is_staff=models.BooleanField(default=False) 
    is_superuser=models.BooleanField(default=True)
    
 
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name','last_name','registration_number']
    
    objects = MyAccountManager()
    
    def __str__(self):
        return self.email
    

     

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from accounts.models import Account


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': 'email'}),
        label=''
    )
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'first name'}),
        label=''
    )
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'last name'}),
        label=''
    )
    registration_number = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Registration Number'}),
        label=''
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Password'}),
        label=''
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}),
        label=''
    )

    class Meta:
        model = Account
        fields = ("first_name", "last_name", "email",
                  'password1', 'password2', 'registration_number')

    def save(self, *args, **kwargs):
        account = super().save(commit=False, *args, **kwargs)
        account.registration_number = self.cleaned_data['registration_number']
        account.save()
        return account


class AccountAuthenticationForm(forms.ModelForm):
    password = forms.CharField(
        label=None, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    email = forms.CharField(label=None, widget=forms.TextInput(
        attrs={'class': 'form-control'}))

    class Meta:
        model = Account
        fields = ('email', 'password')

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("invalid login")

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required

from accounts.forms import RegistrationForm, AccountAuthenticationForm
from rest_framework import viewsets
from rest_framework.decorators import api_view
from rest_framework.decorators import permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from .serializers import UserSerializer
from .models import Account
from .utils import get_user

from summerschool.settings import LOGIN_REDIRECT_URL, LOGIN_URL


def registration_view(request):
    context = {}
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            # email = form.cleaned_data.get('email')
            # raw_password = form.cleaned_data.get('password1')
            # accounts = authenticate(email=email, password=raw_password)
            # login(request, accounts)
            return redirect(reverse('accounts:login'))
        else:
            context['registration_form'] = form

    else:
        form = RegistrationForm()
    context['registration_form'] = form
    return render(request, 'accounts/register.html', context)


def registrationConfirm_view(request):
    return render(request, 'accounts/register_confirm.html')


def logout_view(request):
    logout(request)
    return render(request, 'accounts/logout.html')


def login_view(request):
    context = {}
    user = request.user
    if user.is_authenticated:
        return redirect(reverse(LOGIN_REDIRECT_URL))
    if request.method == 'POST':
        form = AccountAuthenticationForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                return redirect(reverse(LOGIN_REDIRECT_URL))

    else:
        form = AccountAuthenticationForm()

    context['login_form'] = form
    return render(request, 'accounts/login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect(reverse(LOGIN_URL))


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def get_logged_in_user(request):
    context = {}
    serializer = UserSerializer(get_user(request))
    context['user'] = serializer.data
    return Response(context)


@login_required
def home(request, *args, **kwargs):
    return render(request, 'index.html')

accounts/templates/accounts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8" />
		<title>َISTE Summer School Portal | Login</title>

		<link
			rel="stylesheet"
			href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
			integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
			crossorigin="anonymous"
		/>
	</head>

	{% block head %} {% endblock head %}

	<body>
		{% block content %} {% endblock content %}
	</body>
</html>

accounts/templates/accounts/base_1.html
<!DOCTYPE html>
<html lang='en'>
    {% load static %}
<head> 
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, intial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="io-edge">
    <link rel="stylesheet" href="{% static 'accounts/styles.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com"> 
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap" rel="stylesheet">
    
    {% block title %}
        
    {% endblock title %}
        
</head>

<body>
    

{% block content %}
    
{% endblock content %}
    
<footer>
    <p>
      Checkout our website to know more about ISTE Manipal <i class="fa fa-heart"></i> 
      <a target="_blank" href="https://istemanipal.com"></a>
      <!-- Indian Society of Technical Education -->
      <a target="_blank" href="https://istemanipal.com">here</a>.
    </p>
  </footer>
<script src="{% static 'summerschool/script.js'%}"></script>
</body>
</html>

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block head %}
<link href='https://fonts.googleapis.com/css?family=Josefin Sans' rel='stylesheet'>

<style>
  @import url('https://fonts.googleapis.com/css?family=Montserrat:400,800');
  
  * {
    box-sizing: border-box;
  }
  
  body {
    background-image: linear-gradient(#141e30 0%, #243b55 74%);
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    font-family: 'Montserrat', sans-serif;
    height: 95vh;
    margin: -20px 0 50px;
  }
  
  h1 {
    font-weight: bold;
    padding-top: 10px;
    padding-bottom: 10px;
    margin: 0;
  }
  
  h2 {
    text-align: center;
  }
  
  p {
    font-size: 14px;
    font-weight: 100;
    line-height: 20px;
    letter-spacing: 0.5px;
    margin: 20px 0 30px;
  }
  
  span {
    font-size: 12px;
  }
  
  a {
    color: #333;
    font-size: 14px;
    text-decoration: none;
    margin: 15px 0;
  }
  
  button, .button-login {
    border-radius: 20px;
    border: 1px solid #0e0f1f;
    background-color: #161e20;
    color: #FFFFFF;
    font-size: 12px;
    font-weight: bold;
    padding: 12px 45px;
    letter-spacing: 1px;
    cursor: pointer;
    text-transform: uppercase;
    transition: transform 80ms ease-in;
  }
  
  button, .button-login:active {
    transform: scale(0.95);
  }
  
  button:focus {
    outline: none;
  }
  
  button.ghost {

    background-color: transparent;
    border-color: #FFFFFF;
    color: white !important;

  }
  .ghost a{
    color: white;
  }
  form {
    background-color: #FFFFFF;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
    padding: 0 50px;
    height: 100%;
    text-align: center;
  }
  
  input {
    background-color: #eee;
    border: none;
    padding: 12px 15px;
    margin: 8px 0;
    width: 100%;
  }
  
  .container {
    background-color: #fff;
    border-radius: 10px;
      box-shadow: 0 14px 28px rgba(0,0,0,0.25), 
        0 10px 10px rgba(0,0,0,0.22);
    position: relative;
    overflow: hidden;
    width: 768px;
    max-width: 100%;
    min-height: 480px;
  }
  
  .container-2 {
    background-color: #fff;
    border-radius: 10px;
      box-shadow: 0 14px 28px rgba(0,0,0,0.25), 
        0 10px 10px rgba(0,0,0,0.22);
    position: relative;
    overflow: hidden;
    width: 60%;
    max-width: 100%;
    min-height: 1200px;
  }
  
  .form-container {
    position: absolute;
    top: 0;
    height: 100%;
    transition: all 0.6s ease-in-out;
  }
  .form-container {
    position: absolute;
    top: 0;
    height: 100%;
    transition: all 0.6s ease-in-out;
  }
  
  .sign-in-container {
    left: 0;
    width: 50%;
    z-index: 2;
  }
  .sign-in-container-2 {
    left: 50px;
    width: 80%;
    z-index: 2;
  }
  
  .container.right-panel-active .sign-in-container {
    transform: translateX(100%);
  }
  
  .sign-up-container {
    left: 0;
    width: 50%;
    opacity: 0;
    z-index: 1;
  }
  
  .container.right-panel-active .sign-up-container {
    transform: translateX(100%);
    opacity: 1;
    z-index: 5;
    animation: show 0.6s;
  }
  
  @keyframes show {
    0%, 49.99% {
      opacity: 0;
      z-index: 1;
    }
    
    50%, 100% {
      opacity: 1;
      z-index: 5;
    }
  }
  
  .overlay-container {
    position: absolute;
    top: 0;
    left: 50%;
    width: 50%;
    height: 100%;
    overflow: hidden;
    transition: transform 0.6s ease-in-out;
    z-index: 100;
  }
  
  .container.right-panel-active .overlay-container{
    transform: translateX(-100%);
  }
  
  .overlay {
    
    background: #243b55;
 
    background-repeat: no-repeat;
    background-size: cover;
    background-position: 0 0;
    color: #FFFFFF;
    position: relative;
    left: -100%;
    height: 100%;
    width: 200%;
      transform: translateX(0);
    transition: transform 0.6s ease-in-out;
  }
  
  .container.right-panel-active .overlay {
      transform: translateX(50%);
  }
  
  .overlay-panel {
    position: absolute;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
    padding: 0 40px;
    text-align: center;
    top: 0;
    height: 100%;
    width: 50%;
    transform: translateX(0);
    transition: transform 0.6s ease-in-out;
  }
  
  .overlay-left {
    transform: translateX(-20%);
  }
  
  .container.right-panel-active .overlay-left {
    transform: translateX(0);
  }
  
  .overlay-right {
    right: 0;
    transform: translateX(0);
  }
  
  .container.right-panel-active .overlay-right {
    transform: translateX(20%);
  }
  
  .social-container {
    margin: 20px 0;
  }
  
  .social-container a {
    border: 1px solid #DDDDDD;
    border-radius: 50%;
    display: inline-flex;
    justify-content: center;
    align-items: center;
    margin: 0 5px;
    height: 40px;
    width: 40px;
  }
  
  footer {
      background-color: #222;
      color: #fff;
      font-size: 14px;
      bottom: 0;
      position: fixed;
      left: 0;
      right: 0;
      text-align: center;
      z-index: 999;
  }
  
  footer p {
      margin: 10px 0;
  }
  
  footer i {
      color: red;
  }
  
  footer a {
      color: #3c97bf;
      text-decoration: none;
  }
  
  .main-block{
    display: flex;
    flex-direction: row;
  }
  .logo{
    width:400px;
    height:100px;
  }

  
  </style>
  
{% endblock head %}
    
    
{% block content %}

<div class="main-block"></div>
  
    <div class="container d-none d-lg-block" id="container">
    
      <div class="form-container sign-in-container">
        <form class="form-signin text-center" method="POST">
          {% csrf_token %}
          <div class = "logo">
            <img src="{% static 'accounts/iste.png' %}" alt="Iste logo" width="100" height="100">
          </div>
          <h1 style="color: #243b55;" >Sign in</h1>
          <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>   
          
          <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
          <a href="{% url 'password_reset' %}">Forgot your password?</a>
      
    <div class="field">
      <input class="button-login" type="submit" value="Login">
</div>    
  {% if login_form.non_field_errors %}
<div style="color:red;">
    <p>{{login_form.non_field_errors}}</p>
</div>
{% endif %}
</form>
      </div>
      <div class="overlay-container">
        <div class="overlay">
  
          <div class="overlay-panel overlay-right ">
            <h1>Summer School 2021</h1>
            <p>Enter your details and let's learn together!</p>
            <button 
            class="ghost" style="color: wheat !important;" id="signUp"><a href="{% url 'accounts:register' %}">Register</a></button>
          
          </div>
        </div>
      </div>
    </div>


    <div class="container-2 d-lg-none text-center" id="container">
    
      <div class="form-container sign-in-container-2 text-center">
        <form class="form-signin" method="POST">
          {% csrf_token %}
          <div class = "logo" style="margin: 5% !important;">
            <img src="{% static 'accounts/iste.png' %}" alt="ISTE logo" width="100" height="100">
          </div>
          <h1 style="font-size: 430%; margin-bottom: 3%;">Sign in</h1>
          {{login_form}}
          <a style="font-size: 120%;" href="{% url 'password_reset' %}">Forgot your password?</a>
          <a style="font-size: 120%;" href="{% url 'accounts:register'  %}">Not a member yet? Register now!</a>
      
    <div class="field">
      <input style="font-size: 190%;" class="button-login" type="submit" value="Login">
</div>   
  {% if login_form.non_field_errors %}
<div style="color:red;">
    <p>{{login_form.non_field_errors}}</p>
</div>
{% endif %}
</form>
      </div>
     
        </div>
      </div>
    <footer>
      <p>
        Created with ❤️ by
   
        <a target="_blank" href="https://istemanipal.com">ISTE Manipal</a>.
      </p>
    </footer>
  </body>
</html>


  {% endblock content %}
    

accounts/templates/accounts/logout.html
{% extends 'accounts/base.html' %}


{% block head %}
<link href='https://fonts.googleapis.com/css?family=Josefin Sans' rel='stylesheet'>

{% endblock head %}
    
<style>
    html,
body {
  height: 100%;
}

body {
  display: -ms-flexbox;
  display: flex;
  -ms-flex-align: center;
  align-items: center;
  padding-top: 40px;
  padding-bottom: 40px;
  background-color: #f5f5f5;
}
</style>

    
{% block content %}
<div class="container">
    <h1 class="dispplay-1">
        You have logged out of the summer portal
    </h1>
</div>
  {% endblock content %}
    

accounts/templates/accounts/password_reset_complete.html
{% extends 'accounts/base_1.html' %}


{% block content %}

<div class="container">
	<div class="d-flex flex-column">
		<p class="text-sub">Your password has been reset. You may go ahead and <a href="{%url 'accounts:login'%}">sign in</a> now.</p>
	</div>
</div>

{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
<!-- templates/registration/password_reset_confirm.html -->
{% extends 'accounts/base_1.html' %}

{% block title %}Enter new password{% endblock %}
{% block content %}
{% if validlink %}

<p class= "font-title-reset font-weight-normal text-center">Set a new password</p>
<form method="POST" style="text-align: center;">
  {% csrf_token %}
  {{ form.as_p }}
  <input style="margin-top: 3%;" class="text-sub btn-default btn-block" type="submit" value="Change my password">
</form>

{% else %}

<p class="text-sub">The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.</p>

{% endif %}
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'accounts/base_1.html' %}

{% block content %}
<style>
.wrap-this{
}
</style>
<div class="container wrap-this d-flex flex-column" style="margin-top: 20%; margin-bottom: 15%;">

		  <p class="text-sub">
		    We've emailed you instructions for setting your password, if an account exists with the email you entered.
		    You should receive them shortly.
		  </p>
		  <p class="text-sub">
		    If you don't receive an email, please make sure you've entered the address you registered with,
		    and check your spam folder.
		  </p>
		  <hr>
</div>

{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
ISTE Team
{% endautoescape %}

accounts/templates/accounts/password_reset_form.html
{% extends 'accounts/base_1.html' %}


{% block content %}


<div class="pwd-reset-form">
  
<form method="POST" style="margin-top: 10%;" class="form-signin">{% csrf_token %}
  <p class= "font-title-reset font-weight-normal text-center">Reset password</p>
  <p class="text-sub">We will send you a link in the following email id containing instructions to reset your password.</p>
  <input name="email" class="place-default" placeholder="Email address" type="email" id="id_email" required="true">
  <br>
  <button class="text-sub btn-default btn-block" type="submit">Send reset email</button>  
</form>

</div>


{% endblock %}

accounts/templates/accounts/register_confirm.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block head %}
  
{% endblock %}


{% block content %}

<div class="container logout-wrap text-center" style="margin-top: 15%; margin-bottom: 20%;" >
    <h1 style="color: black !important;"> Thankyou for registering </h1> <br>

{% endblock content %}
    